# Generated by Django 3.0 on 2019-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenge4', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='total_comment',
            field=models.IntegerField(default=0),
        ),
    ]
